#!/bin/bash
SCRIPT=$(readlink -f $0)
SCRIPTPATH=`dirname $SCRIPT`
docker run -dt --rm \
	--hostname $1-$2 \
	--name $1-$2 \
	--network $1 \
	-v $SCRIPTPATH/config/:/data/pgsql/config/ \
	-v $SCRIPTPATH/log/:/data/pgsql/log/ \
	-v $SCRIPTPATH/db/:/data/pgsql/db/ \
	$1-$2