#!/bin/bash
SCRIPT=$(readlink -f $0)
SCRIPTPATH=`dirname $SCRIPT`
docker run -dt \
	--hostname $1-$2 \
	--name $1-$2 \
	--network $1 \
	-v $SCRIPTPATH/../../build/:/www/dev.tcss.precess.io/ \
	-v $SCRIPTPATH/../../deploy/:/www/tcss.precess.io/ \
	-v $SCRIPTPATH/config/:/data/nginx/config/ \
	-v $SCRIPTPATH/log/:/data/nginx/log/ \
	-v $SCRIPTPATH/ssl/:/data/nginx/ssl/ \
	$1-$2
