#!/bin/bash
SCRIPT=$(readlink -f $0)
SCRIPTPATH=`dirname $SCRIPT`
docker run -dt \
	--hostname $1-$2 \
	--name $1-$2 \
	--network $1 \
	-v $SCRIPTPATH/../../build/:/www/dev.precess.io/ \
	-v $SCRIPTPATH/../../deploy/:/www/precess.io/ \
	-v $SCRIPTPATH/config/:/data/php-fpm/config/ \
	-v $SCRIPTPATH/log/:/data/php-fpm/log/ \
	$1-$2